---
test:
  terraform_enterprise_defaults: &terraform_enterprise_defaults
    terraform_enterprise_username: username
    terraform_enterprise_password: password
  terraform_enterprise:
    <<: *terraform_enterprise_defaults
